rand-seed-sim: 		 123
#rng seed for world creation#
rand-seed-world: 		 123
#number of cities#
n-cities: 		 300
#maximum distance for link generation#
link-thresh: 	 0.1
#number of departures per time step#
rate-dep: 	 20
#time for departures to reach full rate#
dep-warmup: 	 1.0
#number of exits#
n-exits: 		 10
#number of starting positions#
n-entries: 		 5
#where to start connecting cities to exits#
exit-dist: 	 0.5
#where to stop connecting cities to entries#
entry-dist: 	 0.1
#how many of the closest cities to connect to an entry#
n-nearest-entry:   3
#how many of the closest cities to connect to an exit#
n-nearest-exit:   0
#quality of entries#
qual-entry: 	 0.0
#resources at entries#
res-entry: 	 0.0
#quality of exits#
qual-exit: 	 1
#resources at exits#
res-exit: 	 1
#coordinates of high risk obstacle (rectangle)#
obstacle:	 '[0.4, 0.3, 0.6, 0.7]'
# scale > 1.0 required, otherwise path finding breaks
#how friction scales with distance#
dist-scal:	 '[1.0, 10.0]'
#stochastic range of friction#
frict-range: 	 0.5
#risk on ordinary links#
risk-normal: 	 0.002
#risk on high-risk links#
risk-high: 	 0.1
#expected risk for newly discovered links#
risk-exp: 	 0.01
#scale between 'safe' and 'survivable'#
risk-scale: 	 10.0
#number of contacts when entering#
n-ini-contacts: 		 10
#amount of capital when entering#
ini-capital:  	 2000.0
#set of always unknown cities#
p-unknown-city:   0.0
#set of always unknown links#
p-unknown-link:   0.0
#prob. to know a target when entering#
p-know-target: 	 0.0
#prob. to know a city (per city)#
p-know-city: 	 0.0
#prob. to know a link (per link)#
p-know-link: 	 0.0
#efficiency of exploration for initial knowledge#
speed-expl-ini: 	 1.0
#ercept of risk scoring function#
risk-i: 	 -7.64
#slope of risk scoring function#
risk-s: 	 0.16
#sd of ercept of risk scoring function#
risk-sd-i: 	 4.68
#sd of slope of risk scoring function#
risk-sd-s: 	 0.08
#covariance between ercept and slope of risk scoring function#
risk-cov-i-s: 	 -0.337
#rate at which agents plan their movement after receiving info#
rate-plan: 	 100.0
#expected resources at newly found city#
res-exp: 	 0.5
#expected quality at newly found city#
qual-exp: 0.5
#expected friction for newly found link#
frict-exp: '[1.25, 12.5]'
#prob. to find links when exploring#
p-find-links: 	 0.5
#trust in detected friction/risk for discovered links#
trust-found-links:   0.5
#prob. to find destinations of found links#
p-find-dests: 	 0.3
#trust in information collected while travelling#
trust-travelled: 	 0.8
#efficiency of exploration while staying#
speed-expl-stay: 	 1.0
#efficiency  of exploration while moving#
speed-expl-move: 	 1.0
#rate (frequency) of exploration while staying#
rate-explore-stay: 	 1.0
#probability to notice if contact died#
p-notice-death-c: 	 0.3
#probability to notice if migrant on same link died#
p-notice-death-o:   0.1
#effect on risk perception of contact death#
speed-risk-indir:   0.1
#effect on risk perception of observed death#
speed-risk-obs: 	 0.1
#speed of learning about risk by exploration (relative to other properties)#
speed-expl-risk	: 	 1.0
#rate of costs applying while staying#
rate-costs-stay	: 	 1.0
#resource costs of staying#
costs-stay: 	 1.0
#benefit of resource uptake#
ben-resources	: 	 5.0
#resource costs of moving#
costs-move		: 	 2.0
#when to start saving up capital#
save-thresh		: 	 100.0
#min income required to start saving#
save-income		: 	 1.0
#movement speed#
move-speed		: 	 0.5
#base movement rate#
move-rate		: 	 0.0
#elasticity of traffic counter#
ret-traffic		: 	 0.8
#effect of traffic on current quality#
weight-traffic	: 	 0.001
#effect of proximity to exit on perceived quality#
qual-weight-x	: 	 0.25
#effect of resources on perceived quality#
qual-weight-res	:  	 0.1
#tolerance towards friction when looking for local improvement#
qual-tol-frict	: 	 2.0
#bias of choice towards higher quality#
qual-bias		: 	 1.0
#effect of low location quality on path costs#
path-penalty-loc:   1.0
#effect of risk on path costs#
path-penalty-risk:   5
#prob. to add an agent to contacts#
p-keep-contact 	:  	 0.1
#prob. to lose contact#
p-drop-contact	: 	 0.1
#prob. to exchange info with contacts#
p-info-contacts	: 	 0.1
#prob. to transfer info item#
p-transfer-info: 	 0.1
#maximum number of contacts#
n-contacts-max: 		 50
#learning speed of arrived agents#
arr-learn: 	 0.0
#change doubt o belief#
convince: 	 0.5
#change belief o other belief#
convert: 	 0.1
#change belief o doubt#
confuse: 	 0.3
#stochastic error when transmitting information#
error:  	 0.1
#stochastic error when transmitting risk information#
error-risk:  	 0.01
#stochastic error when transmitting friction information#
error-frict:  	 0.5
#weight of opinion of arrived agents#
weight-arr: 	 1.0
