# information
# probability to lose a contact (per time step and contact)
p_drop_contact:
  min: 0
  max: 1
# probability to communicate with an agent on thecontact list (per contact and time step)
p_info_contacts:
  min: 0
  max: 1
# probability to exchange information while communicating (per item)
p_transfer_info:
  min: 0.05
  max: 1
# amount of noise during information transmission
error:
  min: 0
  max: 0.3
## exploration -----------------------------------------------------------------
# learning speed while moving (only applies to links)
speed_expl_move: 
  min: 0
  max: 1
p_find_links:
  min: 0.05
  max: 1
