# INFO ---------------------------------------------------------
# probability to lose a contact (per time step and contact)
p_drop_contact:
  min: 0
  max: 1
# probability to communicate with an agent on thecontact list (per contact and time step)
p_info_contacts:
  min: 0
  max: 1
# probability to exchange information while communicating (per item)
p_transfer_info:
  min: 0.05
  max: 1
# amount of noise during information transmission
error:
  min: 0
  max: 0.5
# penalty ---------------------------------------------------------
# effect of risk on path costs
path_penalty_risk:
  min: 0
  max: 10
# deaths noticing -----------------------------------------------------
p_notice_death:
  min: 0 
  max: 1
speed_risk:
  min: 0 
  max: 1
speed_expl_stay:
  min: 0 
  max: 1
speed_expl_move:
  min: 0 
  max: 1
# risk scale -----------------------------------------------------
risk_scale:
  min: 4
  max: 18
# departures -----------------------------------------------------
# bit messy
departure1:
  min: 0.2
  max: 3
departure2:
  min: 0.2
  max: 3
departure3:
  min: 0.33
  max: 3
  


